service: startving-app-serverver

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline
custom:
  serverless-offline:
    port: 4001
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true